name: deploy-combo-app

on:
  push:
    branches: [ main ]
    paths:
      - 'nfe-suite/apps/combo_app/**'
      - '.github/workflows/main_nfeapp.yml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # (Sem zip) – manda a pasta do app direto
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: nfeapp
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: nfe-suite/apps/combo_app

